/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author kdeke
 */

public class Administrador extends javax.swing.JFrame {
   Parametrosparapanel.ModeloTablaEditable modelo;
    private JPanel panelContenido;  
    private CardLayout cardLayout;

    Administrador.FondoPanel fondo = new Administrador.FondoPanel();
    
    public Administrador() {
        
        initComponents();
        
        
        //Se crea un modelo de tabla personalizado
       modelo = new Parametrosparapanel.ModeloTablaEditable(
    new Object[][] {
        {"23422", "Casa", "Zona A", "80", "50000", "Disponible", "Ana", "Carlos", ""}
    },
    new String[] {"ID", "Tipo", "Ubicación", "Área", "Precio", "Estado", "Propietario", "Agente", "(Botón)"}
);

jTable1.setModel(modelo);
        mostrarPanelSegunCargo();
        
         fondo.setLayout(new java.awt.BorderLayout());

    // Mueve los paneles existentes al fondo
    fondo.add(AdminBotones, java.awt.BorderLayout.PAGE_START);
    fondo.add(ParentPan, java.awt.BorderLayout.CENTER);
        
        setContentPane(fondo);
    }
    
    private void mostrarPanelSegunCargo() {
    Usuarios cargo = Metodos.getCargo();

    if (cargo != null) {
        String nombreCargo = cargo.getNombreCargo().toLowerCase();
        CardLayout cl = (CardLayout) AdminBotones.getLayout();

        switch (nombreCargo) {
            case "administrador":
                cl.show(AdminBotones, "admin");
                break;
            case "propietario":
                cl.show(AdminBotones, "propietario");
                break;
            case "agente":
                cl.show(AdminBotones, "agente");
                break;
            case "cliente":
            case "visitante":
                cl.show(AdminBotones, "visitante");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Cargo desconocido: " + nombreCargo);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminBotones = new javax.swing.JPanel();
        AgeBotPan = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        VisBotPan = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        ProBotPan = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        AdminBotPan = new javax.swing.JPanel();
        ProAdBot = new javax.swing.JButton();
        CliAdBot = new javax.swing.JButton();
        VisAdBot = new javax.swing.JButton();
        ConAdBot = new javax.swing.JButton();
        PagosAdBot = new javax.swing.JButton();
        RepAdBot = new javax.swing.JButton();
        UsuAdBot = new javax.swing.JButton();
        ParentPan = new javax.swing.JPanel();
        ContratosAdPan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ReportesAdPan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        UsuariosAdPan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ClienPan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PropiPan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        PagosPan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        VisitasPan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminBotones.setLayout(new java.awt.CardLayout());

        AgeBotPan.setBackground(new java.awt.Color(204, 204, 255));

        jButton4.setText("Seguimiento");

        jButton11.setText("Mis Clientes");

        jButton12.setText("Visitas");

        jButton13.setText("Propiedades");

        javax.swing.GroupLayout AgeBotPanLayout = new javax.swing.GroupLayout(AgeBotPan);
        AgeBotPan.setLayout(AgeBotPanLayout);
        AgeBotPanLayout.setHorizontalGroup(
            AgeBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgeBotPanLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        AgeBotPanLayout.setVerticalGroup(
            AgeBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgeBotPanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(AgeBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        AdminBotones.add(AgeBotPan, "agente");

        VisBotPan.setBackground(new java.awt.Color(0, 51, 51));

        jButton3.setText("Mis Contratos");

        jButton18.setText("Buscar Propiedades");

        jButton19.setText("Visitas");

        jButton20.setText("Pagos");

        javax.swing.GroupLayout VisBotPanLayout = new javax.swing.GroupLayout(VisBotPan);
        VisBotPan.setLayout(VisBotPanLayout);
        VisBotPanLayout.setHorizontalGroup(
            VisBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisBotPanLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton18)
                .addGap(18, 18, 18)
                .addComponent(jButton19)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton20)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        VisBotPanLayout.setVerticalGroup(
            VisBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisBotPanLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(VisBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton18)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        AdminBotones.add(VisBotPan, "visitante");

        ProBotPan.setBackground(new java.awt.Color(51, 255, 102));

        jButton2.setText("Mis Propiedades");

        jButton14.setText("Visitas");

        jButton15.setText("Contratos");

        jButton16.setText("Pagos");

        javax.swing.GroupLayout ProBotPanLayout = new javax.swing.GroupLayout(ProBotPan);
        ProBotPan.setLayout(ProBotPanLayout);
        ProBotPanLayout.setHorizontalGroup(
            ProBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProBotPanLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        ProBotPanLayout.setVerticalGroup(
            ProBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProBotPanLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ProBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton14)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        AdminBotones.add(ProBotPan, "propietario");

        AdminBotPan.setBackground(new java.awt.Color(102, 102, 255));
        AdminBotPan.setOpaque(false);

        ProAdBot.setText("Propiedades");
        ProAdBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProAdBotActionPerformed(evt);
            }
        });

        CliAdBot.setText("Clientes");
        CliAdBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliAdBotActionPerformed(evt);
            }
        });

        VisAdBot.setText("Visitas");
        VisAdBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisAdBotActionPerformed(evt);
            }
        });

        ConAdBot.setText("Contratos");
        ConAdBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConAdBotActionPerformed(evt);
            }
        });

        PagosAdBot.setText("Pagos");
        PagosAdBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagosAdBotActionPerformed(evt);
            }
        });

        RepAdBot.setText("Reportes");
        RepAdBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepAdBotActionPerformed(evt);
            }
        });

        UsuAdBot.setText("Usuarios");
        UsuAdBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuAdBotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminBotPanLayout = new javax.swing.GroupLayout(AdminBotPan);
        AdminBotPan.setLayout(AdminBotPanLayout);
        AdminBotPanLayout.setHorizontalGroup(
            AdminBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBotPanLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(ProAdBot)
                .addGap(18, 18, 18)
                .addComponent(CliAdBot)
                .addGap(18, 18, 18)
                .addComponent(VisAdBot)
                .addGap(18, 18, 18)
                .addComponent(ConAdBot)
                .addGap(18, 18, 18)
                .addComponent(PagosAdBot)
                .addGap(18, 18, 18)
                .addComponent(RepAdBot)
                .addGap(18, 18, 18)
                .addComponent(UsuAdBot)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        AdminBotPanLayout.setVerticalGroup(
            AdminBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBotPanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(AdminBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProAdBot)
                    .addComponent(CliAdBot)
                    .addComponent(VisAdBot)
                    .addComponent(ConAdBot)
                    .addComponent(PagosAdBot)
                    .addComponent(RepAdBot)
                    .addComponent(UsuAdBot))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        AdminBotones.add(AdminBotPan, "admin");

        getContentPane().add(AdminBotones, java.awt.BorderLayout.PAGE_START);

        ParentPan.setOpaque(false);
        ParentPan.setLayout(new java.awt.CardLayout());

        ContratosAdPan.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Contratos");

        javax.swing.GroupLayout ContratosAdPanLayout = new javax.swing.GroupLayout(ContratosAdPan);
        ContratosAdPan.setLayout(ContratosAdPanLayout);
        ContratosAdPanLayout.setHorizontalGroup(
            ContratosAdPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratosAdPanLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        ContratosAdPanLayout.setVerticalGroup(
            ContratosAdPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratosAdPanLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        ParentPan.add(ContratosAdPan, "card8");

        ReportesAdPan.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Reportes");

        javax.swing.GroupLayout ReportesAdPanLayout = new javax.swing.GroupLayout(ReportesAdPan);
        ReportesAdPan.setLayout(ReportesAdPanLayout);
        ReportesAdPanLayout.setHorizontalGroup(
            ReportesAdPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportesAdPanLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        ReportesAdPanLayout.setVerticalGroup(
            ReportesAdPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportesAdPanLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        ParentPan.add(ReportesAdPan, "card7");

        UsuariosAdPan.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Usuarios");

        javax.swing.GroupLayout UsuariosAdPanLayout = new javax.swing.GroupLayout(UsuariosAdPan);
        UsuariosAdPan.setLayout(UsuariosAdPanLayout);
        UsuariosAdPanLayout.setHorizontalGroup(
            UsuariosAdPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosAdPanLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        UsuariosAdPanLayout.setVerticalGroup(
            UsuariosAdPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosAdPanLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        ParentPan.add(UsuariosAdPan, "card6");

        ClienPan.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Clientes");

        javax.swing.GroupLayout ClienPanLayout = new javax.swing.GroupLayout(ClienPan);
        ClienPan.setLayout(ClienPanLayout);
        ClienPanLayout.setHorizontalGroup(
            ClienPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienPanLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        ClienPanLayout.setVerticalGroup(
            ClienPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienPanLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        ParentPan.add(ClienPan, "card2");

        PropiPan.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"23422", "Casa ", null, null, null, null, null, null, null},
                {"12342", "Casa", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Ubicación", "Área", "Precio", "Estado", "Propietario", "Agente", "(Boton)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton17.setText("Editar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton21.setText("Guardar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PropiPanLayout = new javax.swing.GroupLayout(PropiPan);
        PropiPan.setLayout(PropiPanLayout);
        PropiPanLayout.setHorizontalGroup(
            PropiPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropiPanLayout.createSequentialGroup()
                .addGroup(PropiPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropiPanLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PropiPanLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jButton17)
                        .addGap(29, 29, 29)
                        .addComponent(jButton21)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        PropiPanLayout.setVerticalGroup(
            PropiPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PropiPanLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PropiPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton21))
                .addGap(13, 13, 13))
        );

        ParentPan.add(PropiPan, "card5");

        PagosPan.setBackground(new java.awt.Color(51, 255, 102));
        PagosPan.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Pagos");

        javax.swing.GroupLayout PagosPanLayout = new javax.swing.GroupLayout(PagosPan);
        PagosPan.setLayout(PagosPanLayout);
        PagosPanLayout.setHorizontalGroup(
            PagosPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagosPanLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        PagosPanLayout.setVerticalGroup(
            PagosPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagosPanLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        ParentPan.add(PagosPan, "card4");

        VisitasPan.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Visitas");

        javax.swing.GroupLayout VisitasPanLayout = new javax.swing.GroupLayout(VisitasPan);
        VisitasPan.setLayout(VisitasPanLayout);
        VisitasPanLayout.setHorizontalGroup(
            VisitasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisitasPanLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        VisitasPanLayout.setVerticalGroup(
            VisitasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisitasPanLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        ParentPan.add(VisitasPan, "card3");

        getContentPane().add(ParentPan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CliAdBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliAdBotActionPerformed
        ParentPan.removeAll();
        ParentPan.add(ClienPan);
        ParentPan.repaint();
        ParentPan.revalidate();
    }//GEN-LAST:event_CliAdBotActionPerformed

    private void ProAdBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProAdBotActionPerformed
        ParentPan.removeAll();
        ParentPan.add(PropiPan);
        ParentPan.repaint();
        ParentPan.revalidate();
    }//GEN-LAST:event_ProAdBotActionPerformed

    private void VisAdBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisAdBotActionPerformed
        ParentPan.removeAll();
        ParentPan.add(VisitasPan);
        ParentPan.repaint();
        ParentPan.revalidate();
    }//GEN-LAST:event_VisAdBotActionPerformed

    private void ConAdBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConAdBotActionPerformed
        ParentPan.removeAll();
        ParentPan.add(ContratosAdPan);
        ParentPan.repaint();
        ParentPan.revalidate();
    }//GEN-LAST:event_ConAdBotActionPerformed

    private void PagosAdBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagosAdBotActionPerformed
        ParentPan.removeAll();
        ParentPan.add(PagosPan);
        ParentPan.repaint();
        ParentPan.revalidate();
    }//GEN-LAST:event_PagosAdBotActionPerformed

    private void RepAdBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepAdBotActionPerformed
        ParentPan.removeAll();
        ParentPan.add(ReportesAdPan);
        ParentPan.repaint();
        ParentPan.revalidate();
    }//GEN-LAST:event_RepAdBotActionPerformed

    private void UsuAdBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuAdBotActionPerformed
        ParentPan.removeAll();
        ParentPan.add(UsuariosAdPan);
        ParentPan.repaint();
        ParentPan.revalidate();
    }//GEN-LAST:event_UsuAdBotActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
 modelo.setEditable(false);
jTable1.repaint();
JOptionPane.showMessageDialog(this, "Cambios guardados.");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
modelo.setEditable(true);
jTable1.repaint();
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminBotPan;
    private javax.swing.JPanel AdminBotones;
    private javax.swing.JPanel AgeBotPan;
    private javax.swing.JButton CliAdBot;
    private javax.swing.JPanel ClienPan;
    private javax.swing.JButton ConAdBot;
    private javax.swing.JPanel ContratosAdPan;
    private javax.swing.JButton PagosAdBot;
    private javax.swing.JPanel PagosPan;
    private javax.swing.JPanel ParentPan;
    private javax.swing.JButton ProAdBot;
    private javax.swing.JPanel ProBotPan;
    private javax.swing.JPanel PropiPan;
    private javax.swing.JButton RepAdBot;
    private javax.swing.JPanel ReportesAdPan;
    private javax.swing.JButton UsuAdBot;
    private javax.swing.JPanel UsuariosAdPan;
    private javax.swing.JButton VisAdBot;
    private javax.swing.JPanel VisBotPan;
    private javax.swing.JPanel VisitasPan;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {
    private Image imagen;

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        imagen = new ImageIcon(getClass().getResource("/imagenes/fondomapa.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        
    }
}
    
}
