/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author kdeke
 */

public class Administrador extends javax.swing.JFrame {
   Parametrosparapanel.ModeloTablaEditable modelo;
    private JPanel panelContenido;  
    private CardLayout cardLayout;

    Administrador.FondoPanel fondo = new Administrador.FondoPanel();
    
    public Administrador() {
        
        initComponents();
        
        
        //Se crea un modelo de tabla personalizado
       modelo = new Parametrosparapanel.ModeloTablaEditable(
    new Object[][] {
        {"23422", "Casa", "Zona A", "80", "50000", "Disponible", "Ana", "Carlos", ""}
    },
    new String[] {"ID", "Tipo", "Ubicación", "Área", "Precio", "Estado", "Propietario", "Agente", "(Botón)"}
);

jTable1.setModel(modelo);
        mostrarPanelSegunCargo();
        
         fondo.setLayout(new java.awt.BorderLayout());

    // Mueve los paneles existentes al fondo
    fondo.add(AdminBotones, java.awt.BorderLayout.PAGE_START);
    fondo.add(ParentPan, java.awt.BorderLayout.CENTER);
        
        setContentPane(fondo);
    }
    
    private void mostrarPanelSegunCargo() {
    Usuarios cargo = Metodos.getCargo();

    if (cargo != null) {
        String nombreCargo = cargo.getNombreCargo().toLowerCase();
        CardLayout cl = (CardLayout) AdminBotones.getLayout();

        switch (nombreCargo) {
            case "administrador":
                cl.show(AdminBotones, "admin");
                break;
            case "propietario":
                cl.show(AdminBotones, "propietario");
                break;
            case "agente":
                cl.show(AdminBotones, "agente");
                break;
            case "cliente":
            case "visitante":
                cl.show(AdminBotones, "visitante");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Cargo desconocido: " + nombreCargo);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminBotones = new javax.swing.JPanel();
        AgeBotPan = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        VisBotPan = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        ProBotPan = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        AdminBotPan = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        ParentPan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        PropiPan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        PagosPan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        VisitasPan = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminBotones.setLayout(new java.awt.CardLayout());

        AgeBotPan.setBackground(new java.awt.Color(204, 204, 255));

        jButton4.setText("Seguimiento");

        jButton11.setText("Mis Clientes");

        jButton12.setText("Visitas");

        jButton13.setText("Propiedades");

        javax.swing.GroupLayout AgeBotPanLayout = new javax.swing.GroupLayout(AgeBotPan);
        AgeBotPan.setLayout(AgeBotPanLayout);
        AgeBotPanLayout.setHorizontalGroup(
            AgeBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgeBotPanLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        AgeBotPanLayout.setVerticalGroup(
            AgeBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgeBotPanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(AgeBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        AdminBotones.add(AgeBotPan, "agente");

        VisBotPan.setBackground(new java.awt.Color(0, 51, 51));

        jButton3.setText("Mis Contratos");

        jButton18.setText("Buscar Propiedades");

        jButton19.setText("Visitas");

        jButton20.setText("Pagos");

        javax.swing.GroupLayout VisBotPanLayout = new javax.swing.GroupLayout(VisBotPan);
        VisBotPan.setLayout(VisBotPanLayout);
        VisBotPanLayout.setHorizontalGroup(
            VisBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisBotPanLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton18)
                .addGap(18, 18, 18)
                .addComponent(jButton19)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton20)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        VisBotPanLayout.setVerticalGroup(
            VisBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisBotPanLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(VisBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton18)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        AdminBotones.add(VisBotPan, "visitante");

        ProBotPan.setBackground(new java.awt.Color(51, 255, 102));

        jButton2.setText("Mis Propiedades");

        jButton14.setText("Visitas");

        jButton15.setText("Contratos");

        jButton16.setText("Pagos");

        javax.swing.GroupLayout ProBotPanLayout = new javax.swing.GroupLayout(ProBotPan);
        ProBotPan.setLayout(ProBotPanLayout);
        ProBotPanLayout.setHorizontalGroup(
            ProBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProBotPanLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        ProBotPanLayout.setVerticalGroup(
            ProBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProBotPanLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ProBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton14)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        AdminBotones.add(ProBotPan, "propietario");

        AdminBotPan.setBackground(new java.awt.Color(102, 102, 255));

        jButton1.setText("Propiedades");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Clientes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Visitas");

        jButton7.setText("Contratos");

        jButton8.setText("Pagos");

        jButton9.setText("Reportes");

        jButton10.setText("Usuarios");

        javax.swing.GroupLayout AdminBotPanLayout = new javax.swing.GroupLayout(AdminBotPan);
        AdminBotPan.setLayout(AdminBotPanLayout);
        AdminBotPanLayout.setHorizontalGroup(
            AdminBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBotPanLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        AdminBotPanLayout.setVerticalGroup(
            AdminBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBotPanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(AdminBotPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        AdminBotones.add(AdminBotPan, "admin");

        getContentPane().add(AdminBotones, java.awt.BorderLayout.PAGE_START);

        ParentPan.setOpaque(false);
        ParentPan.setLayout(new java.awt.CardLayout());

        jPanel1.setOpaque(false);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        ParentPan.add(jPanel1, "card2");

        PropiPan.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"23422", "Casa ", null, null, null, null, null, null, null},
                {"12342", "Casa", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Ubicación", "Área", "Precio", "Estado", "Propietario", "Agente", "(Boton)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton17.setText("Editar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton21.setText("Guardar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PropiPanLayout = new javax.swing.GroupLayout(PropiPan);
        PropiPan.setLayout(PropiPanLayout);
        PropiPanLayout.setHorizontalGroup(
            PropiPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropiPanLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PropiPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17)
                    .addComponent(jButton21))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        PropiPanLayout.setVerticalGroup(
            PropiPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropiPanLayout.createSequentialGroup()
                .addGroup(PropiPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropiPanLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PropiPanLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        ParentPan.add(PropiPan, "card5");

        PagosPan.setBackground(new java.awt.Color(51, 255, 102));
        PagosPan.setOpaque(false);

        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout PagosPanLayout = new javax.swing.GroupLayout(PagosPan);
        PagosPan.setLayout(PagosPanLayout);
        PagosPanLayout.setHorizontalGroup(
            PagosPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagosPanLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        PagosPanLayout.setVerticalGroup(
            PagosPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagosPanLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        ParentPan.add(PagosPan, "card4");

        VisitasPan.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout VisitasPanLayout = new javax.swing.GroupLayout(VisitasPan);
        VisitasPan.setLayout(VisitasPanLayout);
        VisitasPanLayout.setHorizontalGroup(
            VisitasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisitasPanLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        VisitasPanLayout.setVerticalGroup(
            VisitasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisitasPanLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        ParentPan.add(VisitasPan, "card3");

        getContentPane().add(ParentPan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ParentPan.removeAll();
        ParentPan.add(PropiPan);
        ParentPan.repaint();
        ParentPan.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
 modelo.setEditable(false);
jTable1.repaint();
JOptionPane.showMessageDialog(this, "Cambios guardados.");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
modelo.setEditable(true);
jTable1.repaint();
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminBotPan;
    private javax.swing.JPanel AdminBotones;
    private javax.swing.JPanel AgeBotPan;
    private javax.swing.JPanel PagosPan;
    private javax.swing.JPanel ParentPan;
    private javax.swing.JPanel ProBotPan;
    private javax.swing.JPanel PropiPan;
    private javax.swing.JPanel VisBotPan;
    private javax.swing.JPanel VisitasPan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {
    private Image imagen;

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        imagen = new ImageIcon(getClass().getResource("/imagenes/fondomapa.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        
    }
}
    
}
